-- Seed file for local development
-- This file is run after migrations during db reset

-- You can add test users or other seed data here
-- Example:
-- INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at)
-- VALUES (
--   '00000000-0000-0000-0000-000000000000',
--   gen_random_uuid(),
--   'authenticated',
--   'authenticated',
--   'test@example.com',
--   crypt('password', gen_salt('bf')),
--   now(),
--   now(),
--   now()
-- );
